networks:
  traefik:
    name: traefik-net
    external: true
  internal:
    internal: true

services:
  ingestion:
    container_name: rag-ingestion
    image: registry.frba.utn.edu.ar/prd/rag-ingestion

    networks:
      - traefik
      - internal

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rag-ingestion.rule=Host(`rag-ingestion-tst.frba.utn.edu.ar`)"
      - "traefik.http.services.rag-ingestion.loadbalancer.server.port=8001"

    env_file: .env.test
    restart: unless-stopped